local opt = vim.opt
opt.termguicolors = true
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.wo.relativenumber = true
opt.number = true
vim.scriptencoding = "utf-8"
vim.fileencoding = "utf-8"
opt.encoding = "utf-8"
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.wrap = false
opt.scrolloff = 8
opt.signcolumn = "yes"
opt.updatetime = 50
opt.mouse = "a"
opt.clipboard:append("unnamedplus")
opt.ignorecase = true
opt.smartcase = true
